---
- name: Capture alertmanager alerts
  hosts: all
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alert_path: alerts
        data_host_path: labels.instance
        data_path_separator: 
        skip_original_data: true
  rules:
    - name: SELinux was disabled  
      condition: even.alert.labels.alertname == "selinux disabled" and even.alert.status == "firing"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default

