- name: Hello Controller run 100 jobs
  hosts: all
  sources:
    - ansible.EDA-Controller.range:
        limit: 100
  rules:
    - name: "Run job template"
      condition: event.i < 101
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
