- name: listen for events on a webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: http://15.206.165.218:5000/webhook
        port: 5000
  rules:
    - name: Say hello
      condition: event.payload.message == "Ansible is cool"
      action:
        debug:
          msg: 'Webhook triggered!'

    - name: Shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:
