---
- hosts: all
  tasks:
    - name: Install Apache (httpd) package
      package:
        name: httpd
        state: present

    - name: Copy index.html to the remote
      copy:
        src: /home/ec2-user/index.html
        dest: /var/www/html/

    - name: Start the Apache (httpd) service
      service:
        name: httpd
        state: started
